version: '3.8'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - chromadb-server
    environment:
      - CHROMADB_HOST=chromadb-server

  chromadb-server:
    image: chromadb/chroma
    ports:
      - "8000:8000"
